services:
  dinky:
    network_mode: host
    build:
      context: ../..
      dockerfile: ${PWD:-.}/Dockerfile
      args:
        - FLINK_VERSION
        - DINKY_VERSION
    env_file: .env
    volumes:
      - ${CUSTOM_JAR_PATH}:/opt/dinky/customJar/

  jobmanager:
    network_mode: host
    image: flink:${FLINK_VERSION}-scala_2.12-java8
    command: jobmanager
    env_file: .env
    volumes:
      - ${CUSTOM_JAR_PATH}:/opt/flink/lib/customJar/

  taskmanager:
    network_mode: host
    image: flink:${FLINK_VERSION}-scala_2.12-java8
    command: taskmanager
    env_file: .env
    volumes:
      - ${CUSTOM_JAR_PATH}:/opt/flink/lib/customJar/
